# ========================================
# FileName: build.yaml
# Date: 2025-09-16
# Author: (あなた用に再構成)
# Brief: configuration file for ZMK firmware
# Board: mikoto (nRF52840)
# Shield: lily58 (left/right) with nice_view
# =========================================

---
include:
  ### LILY58 START ###
  # --- Lily58 + Mikoto + nice!view（アダプタ無し）---
  - board: mikoto
    shield: lily58_left nice_view
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"Lily58_Mikoto_L\"
    artifact-name: lily58_mikoto_left_niceview

  - board: mikoto
    shield: lily58_right nice_view
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"Lily58_Mikoto_R\"
    artifact-name: lily58_mikoto_right_niceview

  # --- Lily58 + Mikoto + nice!view（アダプタ経由で使う場合）---
  # 必要ならコメントアウトを外して使ってください
  #- board: mikoto
  #  shield: lily58_left nice_view_adapter nice_view
  #  cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"Lily58_Mikoto_L\"
  #  artifact-name: lily58_mikoto_left_niceview_adapter
  #
  #- board: mikoto
  #  shield: lily58_right nice_view_adapter nice_view
  #  cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"Lily58_Mikoto_R\"
  #  artifact-name: lily58_mikoto_right_niceview_adapter

  # --- Lily58 + Mikoto （ディスプレイ無効・切り分け用）---
  - board: mikoto
    shield: lily58_left
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"Lily58_Mikoto_L_ND\"
    artifact-name: lily58_mikoto_left_nodisplay

  - board: mikoto
    shield: lily58_right
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"Lily58_Mikoto_R_ND\"
    artifact-name: lily58_mikoto_right_nodisplay

  # --- 設定消去用（nRF52840/Mikoto 向け）---
  - board: mikoto
    shield: settings_reset
    artifact-name: mikoto_settings_reset
  ### LILY58 END ###
